version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.2
    ports:
      - 3181:3181
    environment:
      ZOOKEEPER_CLIENT_PORT: 3181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:5.1.2
    ports:
      - 10092:10092
      - 30092:30092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:3181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:10092,PLAINTEXT_HOST://localhost:30092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - zookeeper
  schema-registry:
    image: confluentinc/cp-schema-registry:5.1.2
    ports:
      - 9081:9081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:9081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:10092
    depends_on:
      - kafka
      - zookeeper
  redis:
    image: redis:latest
    ports:
      - 6379:6379
